### ISSUE TITLE
モデルにtransformerを追加する

### ISSUE THREAD

**Issue by oki5656** [oki5656/research_orientation_estimation#16]
## Overview
モデルにtransformerを追加する
引数でモデルを選択できるようにする

## ToDo
- [x] developから16_add_transformerを追加
- [x] `models/__init__.py`を作成
- [x] encoder-decoder transformerを実装
- [x] encoderのみのtransformerを実装
- [x] parserを追加（調べながら）
- [x] 距離の誤差を表示できるようにする
- [ ] ~モデルの引数によって最適化関数が変わるように実装~
- [x] PR
- [x] マージ
