### ISSUE TITLE
add test and validation process

### ISSUE THREAD

**Issue by oki5656** [oki5656/research_orientation_estimation#40]
## Overview
今までtrainとvalしか行ってきていなかったのでtrain, val, testに分けて学習できるようにする
実装としては２つ
- [x] train.py
  - [x] パスをvalとtestに分ける
  - [x] 処理の最後にtest()関数を作り，valで一番MDEが低いウェイトパスを用いtestデータで検証できるようにする
- [x] test.pyを作成し，一応test結果を表示できるようにする

## ToDo
- [x] branch developから40_add_test_and_valを作成
- [x] 実装
- [x] PR
- [x] マージ

**Comment by oki5656** [comment]
Done
