### ISSUE TITLE
加速度値の正規化

### ISSUE THREAD

**Issue by oki5656** [oki5656/research_orientation_estimation#57]
## Overview
加速度（Ax, Ay, Az）には大きさのばらつきがあり学習に影響が出ると予測されるため，正規化を行う
ばらつきの影響は重力加速度によるため，重力加速度をキャンセルしなるべく人の動きだけによって発生した加速度を入力したい．よって以下３点の処理を行う
１．重力加速度方向と歩容による加速度方向の合力方向を算出
２．合力方向から距離9.8分の成分をベクトルの要素から引く
３．学習モデルの食わせる

## ToDo
- [x] branch developから57_normalization_of_accelerationを作成
- [ ] 実装
  - [ ] train.py
  - [ ] draw_next_step_result.py
  - [ ] predict_draw_trajectory.py
- [ ] PR
- [ ] マージ
